drop table rename_me;
create memory table rename_me (
	id			int 			generated by default as identity (start with 1 increment by 1) PRIMARY KEY,
	name		varchar(100)
);

insert into rename_me(id, name) values(1, 'Name 1');
insert into rename_me(id, name) values(2, 'Name 2');
insert into rename_me(id, name) values(3, 'Name 3');
insert into rename_me(id, name) values(4, 'Name 4');